configfile: "snakefiles/kraken/config.yaml"
workdir: config['workdir']

SAMPLES, = [config['sample']]

rule get_kraken_db:
    input:
        config['kraken_db']
    output:
        directory("classified/kraken_db")
    shell:
        'ln -s "{input}" {output}'

rule prepare_krona:
    output:
        "classified/taxonomy.tab"
    shell:
        """
        if [ ! -f classified/taxonomy.tab ]; then
        ktpath=$(which ktImportTaxonomy) 
        ktroot=${{ktpath%?????????????????}}     
        bash $ktroot/../opt/krona/updateTaxonomy.sh
        ln -s $ktroot/../opt/krona/taxonomy/taxonomy.tab classified/taxonomy.tab
        fi
        """
    
rule binlorry:
    input:
        demuxed="demuxed/{sample}.fastq"
    params:
        min_length=config["min_length"],
        max_length=config["max_length"],
    output:
        binned="binned/{sample}_{barcode}.fastq"
    shell:
        """
        binlorry -i {input.demuxed} \
        -n {params.min_length} \
        -x {params.max_length} \
        --o binned/{sample} \
        --bin-by barcode
        """

BARCODES, = glob_wildcards("binned/{barcode}_*.fastq")

rule kraken_classify:
    input:
        db="classified/kraken_db",
        binned="binned/{sample}_{barcode}.fastq",
        taxonomy="classified/taxonomy.tab"
    output:
        kraken="classified/barcode_{barcode}/{sample}.kraken",
    shell:
        """
        kraken2 --db {input.db} \
            --memory-mapping \
            {input.binned} \
            > {output.kraken};
        cat {output.kraken} >> classified/barcode_{barcode}/all.kraken;
        ktImportTaxonomy -q 2 -t 3 classified/all.kraken -o classified/barcode_{barcode}/all_krona.html &> classified/barcode_{barcode}/krona.log
        """

rule all:
    input:
        expand("classified/barcode_{barcode}/{sample}.kraken", sample=SAMPLES, barcode=BARCODES)
