name: artic-rampart
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.6
  - biopython=1.70=np112py36_1
  - mappy=2.10=py36_1
  - minimap2=2.10=1
  - watchdog=0.8.3=py36_0
  - yarn=1.10.1
  - nodejs=10.4.1
  - pip
  - pip:
    - msgpack==0.5.6

  - kraken2=2.0.8-beta
  - snakemake=5.4.3
  - krona=2.7.1
